### ISSUE TITLE
R&D Suppress components from search results

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#124]
### Descriptive summary

Please look into our options for suppressing components from search results. Using a custom SearchBuilder, or whatever makes most sense.

If a possible solution is found, please post screenshots and we can potentially move towards a PR in this ticket as well.

### Rationale

While we don't yet know exactly what we want the user experience to be, as it relates to components, we do know that we want them suppressed from the search results interface.

### Expected behavior

A user searches for "fish" and a component with that metadata will show in the search results. We only want the top-level object to be returned, not the component.

### Actual behavior

All matching records, including components, are returned in the search results.

**Comment by VivianChu** [comment]
@mcritchlow - For a new component object , I made a simple change by making the default value "suppress_discovery" instead of "restricted".  For other new object resource object, the default value is still "restricted".  This will suppressed the components in the search results.  Attached are the screen shot.  
![searchcomponent](https://user-images.githubusercontent.com/1864660/28739908-d9792a9a-73b3-11e7-9afb-3925daa4ad42.png)
![objectwithcomponent](https://user-images.githubusercontent.com/1864660/28739907-d977bc82-73b3-11e7-8833-a2bdbeb1f82b.png)
![addnewcomponent](https://user-images.githubusercontent.com/1864660/28739909-d97ba298-73b3-11e7-8881-f99ed4ea98a6.png)
