### ISSUE TITLE
Update Circle CI Ruby version to latest possible

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#32]
Following up on #13:

Please update Ruby to the latest version possible. There was a noted issue with 2.4.0, but hopefully we can either get past that, or at least upgrade to the latest 2.3.x

**Comment by hweng** [comment]
@mcritchlow I've tested to upgrade to ruby 2.4.0 on billing-ill first and it got failed, which is the same errors as the horton upgrades:

```
An error occurred while installing json (1.8.3), and Bundler
cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.
➜  billing-ill git:(feature/upgrade_ruby2.4.0) gem install json -v '1.8.3'
Building native extensions.  This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.
```

Look at https://github.com/rails/rails/issues/27450, "Component 'json' of Ruby on Rails not working with Ruby 2.4.0". it seems the common issue for Ruby 2.4.0

I will try the workaround approaches to see if it can fix the issues.

**Comment by mcritchlow** [comment]
@hweng yeah, this is what @VivianChu ran into as well.

Sounds good on trying workaround ideas.

Worst case, maybe we update to the latest 2.3.x for now and then try again for 2.4 later?

**Comment by hweng** [comment]
@mcritchlow Someone suggested gem json -v 1.8.5 is support it, and It has been published last month.
Let me try it to see how it is going on.

**Comment by hweng** [comment]
@mcritchlow I've tried it on billing-ill, then it comes up different errors one by one which requires to upgrade a bunch of gems but mainly are rails 5 , rspec-rails and rubocop dependency gems.
Now the bundle install in circleci looks fine to me that all gem install errors are gone. It passed DEPENDENCIES, DATABASE step and moved to TEST step:
https://circleci.com/gh/ucsdlib/billing-ill/57?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
The Rspec is fine. It is failed because the RuboCop offenses that after upgrade the RuboCop gem, it detected new 106 offenses.  I'll look into those new offenses and fix them late.

But for horton project it hasn't installed RuboCop so I think it will be fine.
