### ISSUE TITLE
Review statistics gathering options

### ISSUE THREAD

**Issue by mcritchlow** [ucsdlib/horton#86]
### Descriptive summary

In addition to Google Analytics, we have two services that we can potentially use to pull data from for DAMS5.

* Splunk
* Sawmill

Sawmill was purchased because it offered the following:
* Much more granular Wowza streaming statistics than we can get otherwise
* The opportunity to create custom reporting dashboards that users can use themselves to prepare reports

Please look into the pros/cons of these services in comparison to the specifications we have for DAMS5 stats. Potential options to consider:

1. Use only Splunk (and GA) API for DAMS5
2. Use only Sawmill (and GA) API for DAMS5
3. Create reporting experience entirely within Sawmill
4. ..

### Rationale

In order to be able to properly implement DAMS5 statistics, we need to completely understand what our best options are. This is an R&D ticket.

### Related work

A dependency for #41

**Comment by VivianChu** [comment]
@mcritchlow - There is not really a direct API library for Sawmill.  We could use the Enterprise version to populate an SQL database and then use SQL queries to report things that we are interested in.  Currently our Sawmill uses internal database, we couldn't use SQL queries.  We could use the Custom Action to define our action like retrieving which fields that we are interested. 
https://www.sawmill.net/cgi-bin/sawmill8/docs/sawmill.cgi?dp+docs.technical_manual.customactions
I tried to use the existing get_report action and was able to retrieve some data.  Attached are the screen shot.  Some of fields are not display using get_report action and they're displayed fine from the Admin dashboard UI.
Creating custom action is more complicated because it uses Salang (Sawmill language).   I haven't ask Ron to populate the Sawmill with ruby log yet because I'm not sure about which one we will decide to use.
There is Splunk API, good documentation and a ruby gem for our ruby app.  The streaming logs and ruby log are already populated.  It's easier to use.  The performance can be slow depending on the date range.
There is Google Analytics API Client Library for Ruby.  It's also easy to use and fast.
It depends on our Statistic Requirements.  What do you think?  Thanks

**Comment by VivianChu** [comment]
![logdetailreport](https://cloud.githubusercontent.com/assets/1864660/25544744/bbf65410-2c10-11e7-9df3-97c047e0dbf9.png)
![sawmilloverviewreport](https://cloud.githubusercontent.com/assets/1864660/25544754/c2452aa8-2c10-11e7-826f-d9bb80169af7.png)
![filetypereport](https://cloud.githubusercontent.com/assets/1864660/25544756/c5a539f4-2c10-11e7-8ab9-592d62693f25.png)
![streamingreport](https://cloud.githubusercontent.com/assets/1864660/25544764/d24bff76-2c10-11e7-8cc1-1e8505f791f5.png)
